name: version_bmp
description: Bumps the version of the pubspec.yaml
repository: https://github.com/johannesjahn/dart_version_bumper
version: 1.2.4

executables:
  version_bmp: version_bmp

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.7.0
  git: ^2.3.2
